# Generated by Django 4.0.2 on 2022-03-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('ip', models.CharField(max_length=11)),
                ('date_create', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GodURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('ip', models.CharField(max_length=11)),
                ('date_create', models.TimeField()),
            ],
        ),
    ]
