# Generated by Django 4.0.3 on 2022-03-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badurl',
            old_name='date_create',
            new_name='date_create_domain',
        ),
        migrations.RenameField(
            model_name='godurl',
            old_name='date_create',
            new_name='date_create_domain',
        ),
        migrations.AddField(
            model_name='badurl',
            name='asn',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badurl',
            name='country_code',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badurl',
            name='isp',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badurl',
            name='phishstats_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badurl',
            name='phishtank_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badurl',
            name='target',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='godurl',
            name='asn',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='godurl',
            name='country_code',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='godurl',
            name='isp',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='godurl',
            name='phishstats_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='godurl',
            name='phishtank_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='godurl',
            name='target',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
