# Generated by Django 4.0.3 on 2022-03-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0002_rename_date_create_badurl_date_create_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badurl',
            name='date_create_domain',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='godurl',
            name='date_create_domain',
            field=models.TimeField(null=True),
        ),
    ]
