# Generated by Django 4.0.3 on 2022-03-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0003_alter_badurl_date_create_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badurl',
            name='id',
        ),
        migrations.RemoveField(
            model_name='godurl',
            name='id',
        ),
        migrations.AlterField(
            model_name='badurl',
            name='url',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='godurl',
            name='url',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
