# Generated by Django 4.0.3 on 2022-04-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0009_alter_badurl_ip_alter_godurl_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badurl',
            old_name='date_create_domain',
            new_name='create_domain',
        ),
        migrations.RenameField(
            model_name='godurl',
            old_name='date_create_domain',
            new_name='create_domain',
        ),
        migrations.RemoveField(
            model_name='badurl',
            name='country_code',
        ),
        migrations.AddField(
            model_name='badurl',
            name='expiration_domain',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='godurl',
            name='expiration_domain',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
