# Generated by Django 4.0.3 on 2022-04-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0010_rename_date_create_domain_badurl_create_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badurl',
            name='is_phishing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='godurl',
            name='is_phishing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
